5 Cups milk, it should be a bit thick like cream like that. (just put normal milk it will be alright after fully cooked)

some rice (dont put a lot) my mom always say u have to put less rice because it will get thick later.

some sugar based upon your taste.

some dry fruits. 

some cardamoms (but make sure when u r serving , remove it from the plate , its just for good smell and stuff, but it taste bad).

and last some crushed almonds for decoration :)